### ISSUE TITLE
Properly handling files in use and zero-bytes files.

### ISSUE THREAD

**Issue by RCECoder** [kuba--/zip#229] opened 2022-01-10 05:41 UTC
If a file is in use, the `zip_entry_fwrite` will return **ZIP_EWRTDIR -15**
In that case, the file is actually created in the zip archive but with 0 bytes in size.
So how to handle this situation?
I tried calling `zip_entry_close ` then `zip_entries_delete` and I got return value of 1 which means the file with 0 bytes is deleted. However, the next call to `zip_entry_open`/`zip_entry_fwrite`/`zip_entry_close `will crash the application. 
Precisely the call to `zip_entry_close `in the sequence above.
zip_open is called with 'w' flag. Is this a bug?

**Comment by kuba--** [comment] 2022-01-10 09:05
I'm not sure If I fully understand your usecase, but generally You can't call `_open`  twice on already opened entry. Also you can't share zip handler on multiple threads (unless you protect it by some mutex).
If you want to append data to the existing entry, you can open `zip` with `'a'` flag.

**Comment by RCECoder** [comment] 2022-01-10 13:57
> I'm not sure If I fully understand your usecase, but generally You can't call `_open` twice on already opened entry. Also you can't share zip handler on multiple threads (unless you protect it by some mutex). If you want to append data to the existing entry, you can open `zip` with `'a'` flag.

The file in question is in use by another process and not already called  `_open` twice on it.
eg, an external file that has been opened with `CreateFile` with 0 in sharing mode . Now if use `zip_entry_fwrite ` function on that file, it will be created with 0 bytes size in the archive due to sharing violation.
Then to remove that file in the zip archive, I used `zip_entry_close ` followed by `zip_entries_delete`.
After that, a call to `zip_entry_open`/`zip_entry_fwrite`/`zip_entry_close `(for any other accessible file) will crash the app.
the call to zip_entry_close will cause the crash.

**Comment by kuba--** [comment] 2022-01-10 16:43
Ok, I get it.
First of all, `zip_entries_delete` does not physically delete any entries (just mark entries to delete), so you have to call `zip_close` to update _central directory_.
Also to be able delete entries, you should open the archive in `'d'` mode (like in readme example:
```c
char *entries[] = {"unused.txt", "remove.ini", "delete.me"};

struct zip_t *zip = zip_open("foo.zip", 0, 'd');
{
    zip_entries_delete(zip, entries, 3);
}
zip_close(zip);
```
).

**Comment by RCECoder** [comment] 2022-01-10 17:00
Yes, I saw the example. But there is no combining of flags like 'w' | 'd'.
It is weird since I got return value of 1 from `zip_entries_delete`. Doesn't that mean the function has deleted 1 entry? 
Calling `zip_close `will cause the zip archive to be closed and so another `zip_open` call is required. 
Do you mean closing by `zip_close ` then `zip_open ` .. 'd' to delete and then` zip_close` and `zip_open 'a'` for appending?
Well I have been using `zip_open ` .. 'w' once and then `zip_entry_open`/`zip_entry_fwrite`/`zip_entry_close `sequence to update the archive with files.

**Comment by kuba--** [comment] 2022-01-10 19:49
You can also try to open with `'a'` and delete and write without closing. I've never tried that way, but the code for opening the archive for delete and appending is the same.

**Comment by RCECoder** [comment] 2022-01-11 02:31
No, that causes the same issue of crash whenever next `zip_entry_close ` is encountered. Only by using `zip_close`/`zip_open `with appropriate access it works.
Now I have found another issue and I don't want to open another topic for it.
Files with 0 bytes size if zipped, will make Winrar shows a warning of a corrupted archive if you try to extract that file even though the file extracts fine. Not biggy but maybe can look into it.
<img width="504" alt="Untitled" src="https://user-images.githubusercontent.com/49219670/148870859-78128d3c-8aa5-4824-8ba6-f3e61866f929.png">

**Comment by kuba--** [comment] 2022-01-11 12:08
> No, that causes the same issue of crash whenever next `zip_entry_close ` is encountered. Only by using `zip_close`/`zip_open `with appropriate access it works. 

Yeah, it could be tricky (deleting and appending, especially if you delete and append the same entry).


> Now I have found another issue and I don't want to open another topic for it. Files with 0 bytes size if zipped, will make Winrar display a warning of a corrupted archive if you try to extract that file even though the file extracts fine. Not biggy but maybe can look into it. <img alt="Untitled" width="504" src="https://user-images.githubusercontent.com/49219670/148870859-78128d3c-8aa5-4824-8ba6-f3e61866f929.png">

I'm not sure why winrar shows this warning - is it because the file is really corrupted or just because some entry is an empty file? 
What `zipinfo -v` tells you?
If _zip central directory_ is OK (sizes, offsets, checksums are correct), there is nothing wrong to have empty file.
So the question is - is the _central dir._ really messed up or is it somethign winrar's specific.

**Comment by RCECoder** [comment] 2022-01-11 15:05
Thanks for the reply.
Here is the output of `zipinfo -v`

> Archive:  C:/foo.zip   498 bytes   2 files
> 
> End-of-central-directory record:
> -------------------------------
> 
>   Actual offset of end-of-central-dir record:         476 (000001DCh)
>   Expected offset of end-of-central-dir record:       400 (00000190h)
>   (based on the length of the central directory and its expected offset)
> 
>   This zipfile constitutes the sole disk of a single-part archive; its
>   central directory contains 2 entries.  The central directory is 192
>   (000000C0h) bytes long, and its (expected) offset in bytes from the
>   beginning of the zipfile is 208 (000000D0h).
> 
>   There is no zipfile comment.
> warning [C:/foo.zip]:  76 extra bytes at beginning or within zipfile
>   (attempting to process anyway)
> error [C:/foo.zip]:  reported length of central directory is
>   -76 bytes too long (Atari STZip zipfile?  J.H.Holm ZIPSPLIT 1.1
>   zipfile?).  Compensating...
> 
> Central directory entry # 1:
> ---------------------------
> 
>   C:/New Folder/New folder/2.docx
> 
>   offset of local header from start of archive:     0 (00000000h) bytes
>   file system or operating system of origin:        MS-DOS, OS/2 or NT FAT
>   version of encoding software:                     0.0
>   minimum file system compatibility required:       MS-DOS, OS/2 or NT FAT
>   minimum software version required to extract:     2.0
>   compression method:                               deflated
>   compression sub-type (deflation):                 normal
>   file security status:                             not encrypted
>   extended local header:                            yes
>   file last modified on (DOS date/time):            2022 Jan 6 15:42:08
>   32-bit CRC value (hex):                           00000000
>   compressed size:                                  0 bytes
>   uncompressed size:                                0 bytes
>   length of filename:                               31 characters
>   length of extra field:                            4 bytes
>   length of file comment:                           0 characters
>   disk number on which file begins:                 disk 1
>   apparent file type:                               binary
>   non-MSDOS external file attributes:               81B600 hex
>   MS-DOS file attributes (00 hex):                  none
> 
>   The central-directory extra field contains:
>   - A subfield with ID 0x0001 (PKWARE 64-bit sizes) and 0 data bytes.
> 
>   There is no file comment.
> 
> Central directory entry # 2:
> ---------------------------
> 
>   There are an extra 24 bytes preceding this file.
> 
>   C:/New Folder/New folder (2)/New Microsoft Word Document.docx
> 
>   offset of local header from start of archive:     89 (00000059h) bytes
>   file system or operating system of origin:        MS-DOS, OS/2 or NT FAT
>   version of encoding software:                     0.0
>   minimum file system compatibility required:       MS-DOS, OS/2 or NT FAT
>   minimum software version required to extract:     2.0
>   compression method:                               deflated
>   compression sub-type (deflation):                 normal
>   file security status:                             not encrypted
>   extended local header:                            yes
>   file last modified on (DOS date/time):            2022 Jan 10 23:38:58
>   32-bit CRC value (hex):                           00000000
>   compressed size:                                  0 bytes
>   uncompressed size:                                0 bytes
>   length of filename:                               61 characters
>   length of extra field:                            4 bytes
>   length of file comment:                           0 characters
>   disk number on which file begins:                 disk 1
>   apparent file type:                               binary
>   non-MSDOS external file attributes:               81B600 hex
>   MS-DOS file attributes (00 hex):                  none
> 
>   The central-directory extra field contains:
>   - A subfield with ID 0x0001 (PKWARE 64-bit sizes) and 0 data bytes.
> 
>   There is no file comment.
> 
> note:  didn't find end-of-central-dir signature at end of central dir.

**Comment by RCECoder** [comment] 2022-01-11 18:45
Thanks. 
Just noticed, if someone else runs into my problem, the issue of accessing files opened by `CreateFile` with 0 in `dwShareMode` seems to be solved by defining `ZIP_ENABLE_SHARABLE_FILE_OPEN`

**Comment by kuba--** [comment] 2022-03-12 22:00
@RCECoder -
I think I found a problem with empty entries (already merged PR was here: https://github.com/kuba--/zip/pull/245).

IMO it should fix the problem with _corrupted archive_ with empty entries (with compression level > 0).
But maybe it also fixes the previous issue, where you tried to delete and recreate an entry (without closing the whole archive, e.g.:
```c
struct zip_t *zip = zip_open("/tmp/test.zip", 1, 'a');
zip_entry_open(zip, "empty.txt");
zip_entry_close(zip);

zip_entries_delete(zip, (char* []){"empty.txt"}, 1);

zip_entry_open(zip, "empty.txt");
//...
zip_entry_close(zip);

zip_close(zip);
```

PTAL!

**Comment by RCECoder** [comment] 2022-03-14 02:57
Great news!
Yes, I tested and the issue seems to be resolved.
The 0 files are no longer corrupting the archives. However, there maybe a bug if you try to use `zip_entries_delete` with a non-existent file. The crash I got is an exception of `C0000374` which seems to be a heap corruption. Not too important since I added a small line of code which avoids the writing of 0 bytes files in the first place inside `zip_entry_fwrite ` function.
ie,

```
 if (file_stat.st_size == 0) {
	  return ZIP_ZEROFILE //-30;
  }
```

**Comment by kuba--** [comment] 2022-04-09 23:36
@RCECoder - I tried to reproduce it, but I could not. 
It works as expected, with following code:
```
zip = zip_open(ZIPNAME, 0, 'd');
char *fake_entries[] = {"fake1", "fake2"};
mu_assert_int_eq(0, zip_entries_delete(zip, fake_entries, 2));
zip_close(zip);
```

The only way I could get `segmentation fault`  is when I opened the `zip` in `read` mode and tried to delete entries:
```
zip = zip_open(ZIPNAME, 0, 'r');
char *fake_entries[] = {"fake1", "fake2"};
zip_entries_delete(zip, fake_entries, 2);
zip_close(zip);
```

or when I tried to call `zip_entries_delete` without opening `zip`, just:
```
char *fake_entries[] = {"fake1", "fake2"};
zip_entries_delete(zip, fake_entries, 2);
```

**Comment by RCECoder** [comment] 2022-04-11 02:52
I think you are right. I tried it and got the same result as yours. Therefore, this issue is now resolved.

**Closed** 2022-04-17 12:30 UTC
Labels: question
